### ISSUE TITLE
iOS support possible?

### ISSUE THREAD

**Issue by Noitidart** [ajaysaini-sgvu/react-native-schedule-sms#5]
Is this module possible on iOS? It is very cool! Thanks for it!

**Comment by ajaysaini-sgvu** [comment]
@Noitidart Thank you. Apple doesn't allow to send SMS in background without user intervention. It opens SMS composer window to send it.  This is the reason I targeted it for android, Do you have any suggestions ?

**Comment by Noitidart** [comment]
Drats, thanks for your fast reply. I don't have any ideas on how to get around it. :( Thank you sir once again.
